version: "3.9"

services:
  app:
    build: .
    container_name: wandercult
    ports:
      - "${PORT}:${PORT}"             # Use the same port from env
    depends_on:
      - mongodb
    networks:
      - mynetwork
    volumes:
      - ./uploads:/app/uploads
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      API_KEY: ${API_KEY}
      API_BASE_URL: ${API_BASE_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      REDIS_URL: ${REDIS_URL}
      MONGO_URI: ${MONGO_URI}
      PORT: ${PORT}

  mongodb:
    image: mongo:6.0
    container_name: mongowandercult
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

volumes:
  mongo-data:

networks:
  mynetwork:
