version: "3.9"

services:
  app:
    build: .
    container_name: wandercult
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - mynetwork
    volumes:
      - ./uploads:/app/uploads
    environment:
      - MONGO_URI=mongodb://mongowandercult:27017/auth_Wandercult

  mongodb:
    image: mongo:6.0
    container_name: mongowandercult
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

volumes:
  mongo-data:

networks:
  mynetwork:
