version: "3.9"

services:
  app:
    build: .
    container_name: wandercult
    ports:
      - "4000:4000"                   # Host port:Container port
    depends_on:
      - mongodb
    networks:
      - mynetwork
    volumes:
      - ./uploads:/app/uploads
    environment:
      # Match your .env values
      PORT: 4000
      MONGO_URI: mongodb://mongowandercult:27017/auth_Wandercult
      GOOGLE_CLIENT_ID: oiuytrezjhh
      GOOGLE_CLIENT_SECRET: moiuyjhtg
      REDIS_URL: redis://localhost:6379
      SESSION_SECRET: yourStrongSecretKey
      API_KEY: your_api_key_here
      API_BASE_URL: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

  mongodb:
    image: mongo:6.0
    container_name: mongowandercult
    restart: always
    ports:
      - "27018:27017"                  # Host:Container
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

volumes:
  mongo-data:

networks:
  mynetwork:
